#!/bin/sh
#
# kibana4
#
# chkconfig:   2345 81 19
# description: kibana init script
#

# include function library
. /etc/rc.d/init.d/functions

NAME="kibana"
PID_FILE="/var/run/${NAME}.pid"
LOCK_FILE="/var/lock/subsys/${NAME}"
EXEC_PATH="/usr/local/kibana/bin/kibana"
RETVAL=0

run_kibana() {
    if test -f ${PID_FILE}; then
      echo_failure
      return 1
    fi
    nohup ${EXEC_PATH} >/dev/null 2>&1 &
    echo $! > $PID_FILE
    echo_success
    return 0
}

start() {
    echo -n $"Starting ${NAME}: "
    run_kibana
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch ${LOCK_FILE}
}
stop() {
    echo -n $"Stopping ${NAME}: "
    killproc -p ${PID_FILE} $EXEC_PATH
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${LOCK_FILE} {$PID_FILE}
}

if [ $UID != 0 ]; then
    echo '[ERROR] I am not root.'
    exit 1
fi
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status -p ${PID_FILE} $EXEC_PATH
        RETVAL=$?
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        RETVAL=2
        ;;
esac

exit $RETVAL
